# Generated by Django 3.1.2 on 2020-12-04 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first', models.CharField(max_length=20)),
                ('emp_last', models.CharField(max_length=20)),
                ('emp_title', models.CharField(blank=True, choices=[('Ms.', 'MISS'), ('Mr.', 'MR.'), ('Mrs.', 'MRS.'), ('Mx', 'MX')], max_length=4, null=True)),
                ('contact_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lots.contact_information')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_abbrev', models.CharField(max_length=2)),
                ('state_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_rating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.skill')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_skills',
            field=models.ManyToManyField(through='lots.Skill_Level', to='lots.Skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lots.state'),
        ),
    ]
